import type { Metadata } from "next";
import Container from "@/components/layout/Container";
import PageHero from "@/components/layout/PageHero";
import Card from "@/components/ui/Card";
import { site } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy policy for the Trinity Evangelical Lutheran Church website.",
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <PageHero title="Privacy Policy" deck="Last updated: January 13, 2023" />
      <Container className="py-16 sm:py-20">
        {/* TODO: this policy was generated by a free privacy-policy
            generator (per its own text below) and has not been custom
            reviewed for this church's actual data practices — worth having
            it properly reviewed rather than carried over verbatim. */}
        <Card
          accent
          padded={false}
          className="mx-auto flex max-w-3xl flex-col gap-6 p-8 text-ink-muted sm:p-10 [&_h2]:border-t [&_h2]:border-navy-100 [&_h2]:pt-6 [&_section:first-of-type_h2]:border-0 [&_section:first-of-type_h2]:pt-0 [&_ul]:marker:text-gold-600"
        >
          <p>
            This Privacy Policy describes our policies on collecting, using,
            and disclosing information when you use the Service. We use your
            personal data to provide and improve the Service. By using the
            Service, you agree to the collection and use of information in
            accordance with this Privacy Policy.
          </p>

          <section>
            <h2 className="font-heading text-xl font-semibold text-navy">
              Interpretation & Definitions
            </h2>
            <p className="mt-2">
              Capitalized words have meanings defined under the following
              conditions and apply equally in singular or plural forms.
            </p>
            <ul className="mt-3 flex flex-col gap-1 list-disc pl-5">
              <li><strong className="text-ink">Account</strong> — a unique account created to access the Service.</li>
              <li><strong className="text-ink">Company</strong> — {site.name}, {site.address.line1} {site.address.line2}.</li>
              <li><strong className="text-ink">Cookies</strong> — small files placed on your device containing browsing history details.</li>
              <li><strong className="text-ink">Country</strong> — Minnesota, United States.</li>
              <li><strong className="text-ink">Device</strong> — any device that can access the Service.</li>
              <li><strong className="text-ink">Personal Data</strong> — information relating to an identified or identifiable individual.</li>
              <li><strong className="text-ink">Service</strong> — the Website.</li>
              <li><strong className="text-ink">Service Provider</strong> — third parties who process data on the Company&apos;s behalf.</li>
              <li><strong className="text-ink">Usage Data</strong> — information automatically collected from Service use.</li>
              <li><strong className="text-ink">Website</strong> — {site.name}.</li>
              <li><strong className="text-ink">You</strong> — the individual or entity accessing the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-navy">
              Collecting and Using Your Personal Data
            </h2>
            <p className="mt-2">
              We may request that you provide certain personally identifiable
              information, including email address, first and last name,
              phone number, and Usage Data.
            </p>
            <p className="mt-2">
              Usage Data is collected automatically and may include your
              device&apos;s IP address, browser type and version, pages
              visited, time and date of visit, time spent on pages, unique
              device identifiers, and other diagnostic data.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-navy">
              Tracking Technologies and Cookies
            </h2>
            <p className="mt-2">
              We use cookies and similar tracking technologies to track
              activity on our Service and store certain information. Cookie
              categories include:
            </p>
            <ul className="mt-3 flex flex-col gap-1 list-disc pl-5">
              <li>Necessary / Essential Cookies (Session) — enable basic Service features.</li>
              <li>Cookies Policy / Notice Acceptance Cookies (Persistent) — identify acceptance of cookie usage.</li>
              <li>Functionality Cookies (Persistent) — remember choices like login details and preferences.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-navy">
              Use of Your Personal Data
            </h2>
            <p className="mt-2">
              We may use Personal Data to provide and maintain the Service,
              manage your account, contact you about updates, provide news
              and offers (unless you opt out), manage requests, and for data
              analysis to improve our Service.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-navy">
              Retention & Transfer of Your Personal Data
            </h2>
            <p className="mt-2">
              We retain your Personal Data only as long as necessary for the
              purposes set out in this policy, and to comply with legal
              obligations. Your data may be processed at locations outside
              your jurisdiction; by using the Service you consent to this
              transfer.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-navy">
              Delete Your Personal Data
            </h2>
            <p className="mt-2">
              You have the right to request deletion of the Personal Data we
              have collected about you. You may update, amend, or delete your
              information by contacting us directly.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-navy">
              Disclosure of Your Personal Data
            </h2>
            <p className="mt-2">
              We may disclose Personal Data in connection with a business
              transaction (merger, acquisition, or asset sale), if required
              by law, or in good faith belief that disclosure is necessary to
              protect our rights or comply with a legal obligation.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-navy">
              Security of Your Personal Data
            </h2>
            <p className="mt-2">
              The security of your Personal Data is important to us, but
              remember that no method of transmission over the Internet or
              electronic storage is 100% secure.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-navy">
              Children&apos;s Privacy
            </h2>
            <p className="mt-2">
              Our Service does not address anyone under the age of 13. We do
              not knowingly collect personally identifiable information from
              anyone under 13. If you are a parent or guardian and believe
              your child has provided us with Personal Data, please contact
              us.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-navy">
              Links to Other Websites
            </h2>
            <p className="mt-2">
              Our Service may contain links to other websites not operated by
              us. We advise you to review the Privacy Policy of every site
              you visit and assume no responsibility for third-party content
              or practices.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-navy">
              Changes to this Privacy Policy
            </h2>
            <p className="mt-2">
              We may update this Privacy Policy from time to time. Changes
              are posted on this page, and the &quot;Last updated&quot; date
              at the top reflects the most recent revision.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-navy">
              Contact Us
            </h2>
            <p className="mt-2">
              For questions about this Privacy Policy, contact us at{" "}
              <a href={site.emailHref} className="font-semibold text-navy underline underline-offset-4 decoration-navy/30 hover:text-gold-600 hover:decoration-gold-600">
                {site.email}
              </a>{" "}
              or {site.phone}.
            </p>
          </section>
        </Card>
      </Container>
    </>
  );
}
